### ISSUE TITLE
unit test broken ?

### ISSUE THREAD

**Issue by FredericHeem** [etherex/etherex#9]
```
~/etherex$ py.test -rs|more
============================= test session starts ==============================
platform linux2 -- Python 2.7.6, pytest-2.8.0, py-1.4.30, pluggy-0.3.1
rootdir: /home/frederic/etherex, inifile: setup.cfg
plugins: xdist-1.13.1
collected 55 items

tests/test_etherex.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
tests/test_etx.py EEEEEEE

==================================== ERRORS ====================================
_________________ ERROR at setup of TestEtherEx.test_creation __________________

self = <class 'test_etherex.TestEtherEx'>

    def setup_class(self):
>       self.state = tester.state()

tests/test_etherex.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/dist-packages/ethereum/tester.py:136: in __init__
    self.block = b.genesis(self.env, start_alloc=o)
/usr/local/lib/python2.7/dist-packages/ethereum/blocks.py:1372: in genesis
    block = Block(header, [], [], env=env)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Block(#0 f1e66880)>, header = <BlockHeader(#0 f1e66880)>
transaction_list = [], uncles = []
env = <ethereum.config.Env object at 0x7f00decd7e10>, parent = None
making = False

    def __init__(self, header, transaction_list=[], uncles=[], env=None,
                 parent=None, making=False):
        assert isinstance(env, Env), "No Env object given"
        assert isinstance(env.db, BaseDB), "No database object given"
        self.env = env # don't re-set after init
        self.db = env.db
        self.config = env.config
    
        self.header = header
        self.uncles = uncles
    
        self.uncles = uncles
        self.suicides = []
        self.logs = []
        self.log_listeners = []
        self.refunds = 0
    
        self.ether_delta = 0
        self._get_transactions_cache = []
    
        # Journaling cache for state tree updates
        self.caches = {
            'balance': {},
            'nonce': {},
            'code': {},
            'storage': {},
            'all': {}
        }
        self.journal = []
    
        if self.number > 0:
            self.ancestor_hashes = [self.prevhash]
        else:
            self.ancestor_hashes = [None] * 256
    
        # do some consistency checks on parent if given
        if parent:
            if hasattr(parent, 'db') and self.db != parent.db and self.db.db != parent.db:
                raise ValueError("Parent lives in different database")
            if self.prevhash != parent.header.hash:
                raise ValueError("Block's prevhash and parent's hash do not match")
            if self.number != parent.header.number + 1:
                raise ValueError("Block's number is not the successor of its parent number")
            if not check_gaslimit(parent, self.gas_limit):
                raise ValueError("Block's gaslimit is inconsistent with its parent's gaslimit")
            if self.difficulty != calc_difficulty(parent, self.timestamp):
                raise ValueError("Block's difficulty is inconsistent with its parent's difficulty")
            if self.gas_used > self.gas_limit:
                raise ValueError("Gas used exceeds gas limit")
            if self.timestamp <= parent.header.timestamp:
                raise ValueError("Timestamp equal to or before parent")
            if self.timestamp >= 2**256:
                raise ValueError("Timestamp waaaaaaaaaaayy too large")
    
        for uncle in uncles:
            assert isinstance(uncle, BlockHeader)
    
        original_values = {
            'gas_used': header.gas_used,
            'timestamp': header.timestamp,
            'difficulty': header.difficulty,
            'uncles_hash': header.uncles_hash,
            'bloom': header.bloom,
>           'header_mutable': self.header.mutable_,
        }
E       AttributeError: 'BlockHeader' object has no attribute 'mutable_'

```

**Comment by caktux** [comment]
I'm unable to reproduce the error, and builds on Travis are also fine. Guessing you're on a bad commit of pyethereum, which version is it?
